name: Rust CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Rust dependencies
        run: make install

      - name: Lint Rust code
        run: make lint

      - name: Format Rust code
        run: make format

      - name: Build Rust project
        run: make build

      - name: Run Rust tests
        run: make test

      - name: Build optimized Rust binary
        run: cargo build --release

      - name: Upload optimized Rust binary
        uses: actions/upload-artifact@v3
        with:
          name: rust-binary
          path: target/release/rust_etl_cli

      - name: Run Rust application
        run: make run
